modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Polymeta/Pokegift/issues"
license = "MIT License"

[[mods]]
modId = "pokegift"
version = "${version}"
displayName = "Pokegift"
authors = "Polymeta"
description = '''
Gift your pokemon to players!
'''
#logoFile = ""

[[dependencies.pokegift]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.182,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pokegift]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pokegift]]
modId = "architectury"
mandatory = true
versionRange = "[13.0.6,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.pokegift]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.7.0,)"
ordering = "AFTER"
side = "BOTH"